#! /usr/bin/bash
cd $pathP
if [ -d $1 ]
then
cd $pathP$1
select opt in "Create Table" "List Tables" "Drop Table" "Insert into Table" "Select From Table" "Delete From Table" "Update Table" "exit"
do
case $opt in 
"Create Table")
read -p "enter table name " tbname;
createTB $tbname
;;
"List Tables")
ls
;;
"Drop Table")
read -p "enter table name " tbname;
rm  $tbname
echo "done"
;;
"Insert into Table")
read -p "enter table name " tbname;
insertTB $tbname
;;
esac
done
else
echo "database not exists"
fi
