#! /usr/bin/bash
shopt -s extglob
record="";
let num
case $1 in
+([a-zA-Z])*([0-9]))
if [ -f $1 ]
then
echo "table is exists"
else
touch $1;
record+=$1
read  -p "Typw number columns :" num;
record+='@'$num
x=0
while [ $x != $num ]
do
read -p "Type name column "$(($x+1))' :' nameField;
read -p "Type datatype column "$(($x+1))' :' datatype;
record+='@'$nameField'-'$datatype 
x=$(( $x + 1 ))
done
while [ true ]
do
read -p "Type primary key :" primary;
if [[ $record =~ .*$primary.* ]]
then
record=$record@$primary;
echo $record >> .metadata;
break;
else
echo 'invalid primary key'
fi
done
fi
;;
*)
echo "invalid table name"
;;
esac
