#! /usr/bin/bash
pathP="/home/m7moud/bash_project/DBMS_DBS/";
export pathP
#check connect
select opt in "Create Database" "List Databases" "Connect To Databases" "Drop Database" "exit"
do
case $opt
in
"Create Database")
 read -p "Type database name :" dbname
 createDB $dbname
;;
"List Databases")
dislist $pathP Databases
;;
"Connect To Databases")
 read -p "Type database name :" dbname
if [ -d $pathP$dbname ]
then
gnome-terminal -- bash -c "connectDB $dbname; exec bash"
else 
echo "database $dbname not exists"
fi
;;
"Drop Database")
read -p "Type database name :" dbname
rm -R $pathP$dbname
echo "droped database "$dbname
;;
"exit")
break;
;;
*)
    echo "command error"
    ;;
esac
done
