#! /usr/bin/bash
pathP="/d/DBMS_project/DBMS_DBS/";
export pathP
#check connect
select opt in "Create Database" "List Databases" "Connect To Databases" "Drop Database" "exit"
do
case $opt
in
"Create Database")
 read -p "enter database name " dbname
 createDB $dbname
;;
"List Databases")
ls $pathP
;;
"Connect To Databases")
 read -p "enter database name " dbname
connectDB $dbname
;;
"Drop Database")
read -p "enter database name " dbname
rm -R $pathP$dbname
echo "drop database "$dbname
;;
"exit")
break;
;;
*)
    echo "not nknow command"
    ;;
esac
done