#! /usr/bin/bash
path="/d/DBMS_project/DBMS_DBS/";
#check connect
select opt in "Create Database" "List Databases" "Connect To Databases" "Drop Database" "exit"
do
case $opt
in
"Create Database")
 read -p "enter database name " dbname
 createDB $dbname
;;
"List Databases")
ls $path
;;
"Connect To Databases")
 read -p "enter database name " dbname
connectDB $dbname
;;
"Drop Database")
read -p "enter database name " dbname
rm -R $path$dbname
;;
"exit")
break;
;;
*)
    echo "not nknow command"
    ;;

esac
done