#! /usr/bin/bash
shopt -s extglob
checkType(){ #function
case $1 in
+([0-9]))
echo int
;;
+([A-Za-z])*([A-Za-z0-9]))
echo text
;;
+([0][1-9]|[12][0-9]|[3][01])-+([0][1-9]|[1][0-2])-[2,1][0-9][0-9][0-9]) #01,02---09 10,11,12,1
echo date
;;
*)
echo null
;;
esac
}
record="";
metadata=`cat .metadata | grep "$1@"` #asd@3@id-int@name-text@address-text@id
arrIN=(${metadata//@/ })  #[asd,1,id-int,name-text] 
nameTB=${arrIN[0]};
numField=${arrIN[1]};
primaryKey=${arrIN[$(($numField + 2))]};
x=0
while [ $x != $numField ]
do
field=${arrIN[$(($x+2))]} #id-int
arr2=(${field//-/ }); #[id,int]
read -p "enter "${arr2[0]} f1 #ashdh
if [ ${arr2[0]} == $primaryKey ]
then
 res=`cut -d# -f$(($x+1)) asd | grep $f1 |wc -l`
 if [ $res != 0 ]
 then
 echo 'this value is exists';
 continue;
 fi
fi
result=$(checkType $f1)
if [ $result == ${arr2[1]} ]
then
record+=$f1'#'
x=$(( $x + 1 ))
else
echo "invalid datatype"
fi
done 
echo $record >> $nameTB

